//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoWPF.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Folk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Folk()
        {
            this.Active = new HashSet<Active>();
            this.Active1 = new HashSet<Active>();
            this.Active2 = new HashSet<Active>();
            this.Active3 = new HashSet<Active>();
            this.Active4 = new HashSet<Active>();
            this.Active5 = new HashSet<Active>();
        }
    
        public double ID { get; set; }
        public string ФИО { get; set; }
        public string пол { get; set; }
        public string почта { get; set; }
        public Nullable<System.DateTime> дата_рождения { get; set; }
        public Nullable<double> страна { get; set; }
        public string телефон { get; set; }
        public string направление { get; set; }
        public string пароль { get; set; }
        public string фото { get; set; }
        public string Роль { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Active> Active { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Active> Active1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Active> Active2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Active> Active3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Active> Active4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Active> Active5 { get; set; }
        public virtual Страны Страны { get; set; }
    }
}
